# The figure registry — the single source of truth for what figures exist.
#
# One row per figure, so nothing about a figure can drift between the paper, the deck,
# the poster and the reports. If a figure is
# not in here it does not exist; if a field is empty the figure is not finished.
#
# Every consumer pulls from this table:
#   paper        -> caption, and the rendered file
#   presentation -> shows / reads, and the rendered file at slide size
#   poster       -> the rendered file at poster size
#   reports      -> the whole explainer

#' The canonical figure registry
#'
#' @param consumers Optional character vector; keep only figures consumed by at least one of
#'   these (\code{"paper"}, \code{"slides"}, \code{"poster"}, \code{"report"}).
#' @param status Optional character vector; keep only figures with these statuses
#'   (\code{"built"}, \code{"planned"}).
#' @return A data.frame, one row per figure.
figureRegistry <- function(consumers = NULL, status = NULL) {

  f <- function(id, paperId, title, builder, sources, consumers, status,
                caption, shows, reads, rails = NA_character_) {
    data.frame(id = id, paperId = paperId, title = title, builder = builder,
               sources = sources, consumers = consumers, status = status,
               caption = caption, shows = shows, reads = reads, rails = rails,
               stringsAsFactors = FALSE)
  }

  reg <- rbind(

    f(id       = "v6-strength",
      paperId  = NA_character_,
      title    = "The v6 strength factor k(t) on each energy system",
      builder  = "figV6Strength",
      sources  = "phase1/strength.rds",
      consumers= "report",
      status   = "built",
      caption  = paste("Strength k(t) = G(t)/G(2025), the final-energy-weighted mean regional gap",
                       "relative to 2025, per sector, on the current-policy and 1000 Gt energy",
                       "systems (EU21). Offline Phase 1 reading on fixed REMIND runs."),
      shows    = paste("How the anchored ranking's bite changes over the century, and how much",
                       "the energy system (the REMIND feedback) moves it."),
      reads    = paste("Below 1, every region moves the same fraction towards phi = 1. Compare the",
                       "two lines within a panel for the energy-system effect."),
      rails    = paste("Offline, not a coupled fixed point; the Bulk path depends on the actor-power",
                       "family (family A falls, family B does not, ADR 0052) and on institution",
                       "terms that are not identified. Quote with its Run-Group and bases.")),

    f(id       = "v6-shares",
      paperId  = NA_character_,
      title    = "The v6 feasibility shares: a fixed ranking with a moving strength",
      builder  = "figV6Shares",
      sources  = "phase1/anchors.rds, phase1/strength.rds",
      consumers= "report",
      status   = "built",
      caption  = paste("Feasibility share phi = 1 - theta k(t) u per region and sector at theta = 0.5,",
                       "2025, 2050 and 2100, on the 1000 Gt energy system (EU21). Regions ordered by",
                       "the anchor-year ranking u."),
      shows    = paste("That the order of regions is read once, at the anchor year, and only the",
                       "spread changes with k(t)."),
      reads    = paste("The bottom region holds 1 - theta k(t); the top region holds 1. Starred regions",
                       "carry assigned, not observed, efficiency."),
      rails    = paste("phi is ordinal at a declared theta: 0.5 means 'ranked last', not 'can deliver",
                       "half'. Offline reading.")),

    f(id       = "frontier-fit",
      paperId  = "Fig 1b",
      title    = "Observed stringency against the estimated ceiling",
      builder  = "figFrontierFit",
      sources  = "frontier.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Observed policy stringency against the estimated political ceiling,",
                       "48 in-coverage countries, both sectors, 2022. Each point is a country;",
                       "the diagonal is the ceiling. Vertical distance below it is political",
                       "slack. Points cannot lie materially above the line by construction:",
                       "the frontier is a bound, not a fit through the middle."),
      shows    = paste("That the model produces a *ceiling*, not a conditional mean — the",
                       "defining property of the stochastic frontier, made visual."),
      reads    = paste("The spread of the vertical distances IS the distribution of political",
                       "slack. Diffuse sits closer to its ceiling (median E 0.685) than Bulk",
                       "(0.639), i.e. the demand side is nearer its own political limit."),
      rails    = paste("Do not name individual Bulk countries from this plot — Bulk slack",
                       "ranks are not robust (MODEL.md 3.4). Label Diffuse only.")),

    f(id       = "frontier-coefficients",
      paperId  = "Fig 2a",
      title    = "What sets the ceiling",
      builder  = "figFrontierCoefficients",
      sources  = "frontier.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Contribution of each frontier term to the linear predictor, beta x",
                       "SD of the term, in logits, with 95% confidence intervals, both",
                       "sectors, fixed effects included. Drivers and interaction factors are",
                       "standardized to unit SD so their contribution equals their",
                       "coefficient; the logistic time trend is a raw logistic in [0,1] over",
                       "2001-2022 and is scaled by its own standard deviation of 0.0796.",
                       "Actor-power terms enter saturating and split into innovator and",
                       "incumbent components."),
      shows    = paste("Which channels move the ceiling, that the two sectors are moved by",
                       "different ones, and how much of the movement is calendar time."),
      reads    = paste("The time trend is the largest single term (0.818 Bulk, 0.408",
                       "Diffuse). Government Effectiveness is the largest institutional term",
                       "(0.264 and 0.389) and the most reliable in both sectors. On the Bulk",
                       "side the interactions carry the story, not the actor-power main",
                       "effects."),
      rails    = paste("REVISED 2026-08-18: this plots beta x SD(x), NOT raw coefficients.",
                       "The previous version plotted raw beta on an axis labelled 'per SD',",
                       "which was wrong for the trend (a raw [0,1] regressor, not a per-SD",
                       "quantity) and let its 10.3 compress every political term to an",
                       "unreadable sliver at zero. Do NOT revert. For raw estimates read",
                       "frontier.rds$bySector$<s>$coefTable, or MODEL.md 2.5 for the",
                       "mean-regression table - and quote the SD alongside any raw value.",
                       "Neither Bulk actor-power MAIN effect is significant — do not read a",
                       "main effect off this panel. The Incumbency x GovEff interaction is",
                       "positive where theory expects negative (the unresolved exposure",
                       "confound, MODEL.md 8.3); say so if it is shown.")),

    f(id       = "theta-sweep",
      paperId  = "Fig 3c",
      title    = "What the political ceiling costs the pathway",
      builder  = "figThetaSweep",
      sources  = "coupling/coupling-summary.rds",
      consumers= "paper,slides,poster",
      status   = "built",
      caption  = paste("Median 2050 politically feasible carbon price and the shortfall",
                       "against the cost-optimal path, across the coupling-severity",
                       "parameter theta. The binding share (right axis) is flat: theta sets",
                       "how far below the bound sits, not how often it binds."),
      shows    = "The headline magnitude — how much of the cost-optimal price is unreachable.",
      reads    = paste("At the declared theta = 0.50 the median 2050 feasible price",
                       "is about $184 against a cost-optimal $355, a 48% shortfall, binding",
                       "in 84.5% of region-years. Note theta = 0 is NOT the cost-optimal",
                       "path: it still shows a ~36% shortfall because the speed limit binds",
                       "even when every share is 1."),
      rails    = paste("This is the PFM-side BOUND, not a coupled REMIND result. A coupled",
                       "batch DOES now exist (2026-08-17) - see the coupled-* figures - and",
                       "the two must not be blurred: this 84.5% is where the bound exceeds",
                       "the anchor, while the coupled bind share is 57% (EU21) / 96% (H12).",
                       "Do not call theta = 0.79 the anchor; the anchor is 0.50. Note also",
                       "that revealed preference bounds theta at 0.135 under the",
                       "absolute-level formulation (MODEL.md 5.3.1) - the swept range above",
                       "0.135 is admissible only because REMIND's legislated-price floor",
                       "patches it.")),

    f(id       = "shortfall-regions",
      paperId  = "Fig 3b",
      title    = "Where the ceiling binds",
      builder  = "figShortfallRegions",
      sources  = "coupling/coupling-summary.rds",
      consumers= "paper,slides,poster",
      status   = "built",
      caption  = paste("Regional 2050 carbon-price shortfall against the cost-optimal path",
                       "at the declared theta = 0.50, 21 REMIND regions, ranked.",
                       "The constraint is deeply uneven: the most constrained region gives up",
                       "several times what the least constrained does."),
      shows    = "That the constraint is distributional, not a uniform haircut.",
      reads    = paste("Rank order, not levels. The spread is the story: at theta = 0.50 the",
                       "most constrained region gives up $235/tCO2 and the least $79 - a",
                       "factor of three. Absolute values move with theta; the ordering does",
                       "not."),
      rails    = paste("Levels scale with theta, so the figure prints the value it used in",
                       "its own subtitle and the caption must repeat it. The RANK ORDER is",
                       "theta-invariant and is what this panel is for.",
                       "The USA must be shown as a RANGE or omitted - its feasibility share",
                       "moves across the entire scale under defensible donor rules",
                       "(TODO item 6). Out-of-coverage regions carry a transferred relative",
                       "gap, never a ceiling of their own.")),

    f(id       = "selection-stability",
      paperId  = "Fig 2c",
      title    = "What the data does and does not identify",
      builder  = "figSelectionStability",
      sources  = "selection-bootstrap.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Bootstrap selection frequency against the base rate in the candidate",
                       "pool, 200 resamples. A specification element is only supported where",
                       "it is selected MORE often than its availability in the pool; the gap",
                       "between the open and filled points is the evidence."),
      shows    = paste("Which parts of the specification are identified, and that a raw",
                       "selection frequency alone cannot tell you."),
      reads    = paste("Government Effectiveness survives into 97.5% of the top-40 pool and",
                       "is selected in 91% of resamples - that pool share is the evidence it",
                       "belongs. Split actor power: 72.5% of the pool, 72.0% selected. ANY",
                       "accountability channel: 61.5% of the pool, 63.7% selected -",
                       "indistinguishable (p = .59), so resampling neither supports nor",
                       "further penalises it."),
      rails    = paste("A raw frequency is NOT evidence. The menu offers three accountability",
                       "options against one 'none', so random selection takes accountability",
                       "80% of the time; the tournament's own top 40 carries it only 61.5%,",
                       "i.e. it is demoted relative to availability. Always report the pool",
                       "base rate beside the frequency. This is the honesty exhibit - do not",
                       "soften it.")),

    f(id       = "sector-speeds",
      paperId  = NA_character_,
      title    = "How fast a ceiling can be approached — and what is forecastable",
      builder  = "figSectorSpeeds",
      sources  = "sector-speeds.rds",
      consumers= "slides,poster,report",
      status   = "built",
      caption  = paste("Estimated adjustment speed by sector, with out-of-sample skill",
                       "against a persistence benchmark annotated. Only electricity beats",
                       "\"assume nothing changes\"; the other three rates are descriptive",
                       "bounds, not forecasts."),
      shows    = paste("That speed and *forecastability* are different things — the single",
                       "most under-appreciated point in the model."),
      reads    = paste("Electricity is the only sector with positive skill (+0.106). Industry",
                       "and transport adjust fastest in-sample but have strongly negative",
                       "skill, meaning persistence beats them out of sample."),
      rails    = paste("Never present a negative-skill rate as a forecast. The skill",
                       "annotation must stay ON the figure, not in the caption alone.")),

    f(id       = "saturating-map",
      paperId  = NA_character_,
      title    = "Why actor power must saturate",
      builder  = "figSaturatingMap",
      sources  = "frontier.rds",
      # Run-Group v5 deploys X-2079 with NO saturating transform (bothIncAP, lin). Kept for the
      # specification-menu discussion only; out of the deck and poster (TODO item 24a).
      consumers= "report",
      status   = "built",
      caption  = paste("The parameter-free saturating map applied to actor power before",
                       "standardization, with the estimation range and the range REMIND",
                       "projects into shaded separately. Linear in the share, the model",
                       "would extrapolate its slopes far beyond the range that identifies",
                       "them."),
      shows    = paste("The justification for ADR 0040 in one glance: the gap between where",
                       "the model was estimated and where it is asked to operate."),
      reads    = paste("Bulk innovator power spans roughly 0.03-0.43 in training while REMIND",
                       "takes it to 0.58-0.68 — almost disjoint. The map compresses that",
                       "extrapolation instead of letting slopes run."),
      rails    = "This is a design choice, parameter-free, not an estimate. Say so."),

    f(id       = "efficiency-distribution",
      paperId  = "Fig 1c",
      title    = "Distribution of the efficiency ratio, by how it was obtained",
      builder  = "figEfficiencyDistribution",
      sources  = "frontier.rds,donor-assignment-band-<sector>.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Distribution of the efficiency ratio E = S/S* across all 248",
                       "projected countries, by sector, coloured by provenance. Only 48",
                       "countries are inside the estimation sample; the remainder inherit a",
                       "relative gap through the donor and band rules and are shown",
                       "separately."),
      shows    = paste("The coverage problem in picture form — how much of the projected",
                       "world is transferred rather than estimated."),
      reads    = paste("The two towers are the finding. The lowBand and median branches each",
                       "assign ONE value to every country in them, so 166 of 248 countries",
                       "sit at exactly two points - 96 at the low band and 70 at the median",
                       "per sector. Only the 48 estimated countries have a genuine",
                       "distribution. The low band sits deliberately below the observed",
                       "median: absence of data must not be rewarded with assumed",
                       "capability."),
      rails    = paste("Do NOT build this on projection.rds$implementability — that column",
                       "is exactly index/10, the S/10 multiplier MODEL.md 7 prohibits.",
                       "Verified to machine precision. Use E = S/S*, which means combining",
                       "frontier.rds (48 observed) with the band assignment (200",
                       "transferred); together they partition the 248 exactly.")),

    f(id       = "implementability-map",
      paperId  = "Fig 4a",
      title    = "Where the ceiling is estimated, and where it is not",
      builder  = "figImplementabilityMap",
      sources  = "frontier.rds,donor-assignment-band-<sector>.rds",
      consumers= "paper,slides,poster",
      status   = "built",
      caption  = paste("Estimated efficiency ratio E = S/S* by country, Bulk sector.",
                       "Countries outside the estimation sample are left uncoloured: they",
                       "carry a transferred relative gap, not a measured ceiling, and",
                       "colouring them on the same scale would present an assumption as a",
                       "measurement."),
      shows    = "Both the geographic pattern AND the extent of what is not known.",
      reads    = paste("The grey is the finding as much as the colour is. Read where the",
                       "model has evidence before reading what it says."),
      rails    = paste("Out-of-coverage countries render as ABSENT — never as zero, never",
                       "as the transferred median, never on the same colour scale. 200 of",
                       "248 projected countries are outside the sample. Same S/10",
                       "prohibition as Fig 1c.")),

    f(id       = "implementability-map-full",
      paperId  = NA_character_,
      title    = "Every projected country, with provenance visible",
      builder  = "figImplementabilityMapFull",
      sources  = "frontier.rds,donor-assignment-band-<sector>.rds",
      consumers= "slides,poster,report",
      status   = "built",
      caption  = paste("Efficiency ratio E = S/S* for all 248 projected countries.",
                       "Estimated countries are drawn at full opacity; the 200 that",
                       "receive a transferred relative gap through the donor and band",
                       "rules are faded. Both sit on one colour scale because both",
                       "enter the coupling; the opacity is what separates measurement",
                       "from assumption."),
      shows    = paste("What the coupling actually feeds REMIND, as opposed to what",
                       "was measured."),
      reads    = paste("Compare against the estimated-only map: the faded mass is how",
                       "much of the delivered constraint rests on transfer rules",
                       "rather than on data."),
      rails    = paste("Never present this without the opacity distinction, and never",
                       "as the paper's coverage figure - use implementability-map for",
                       "that. A transferred gap is an assumption with a stated rule,",
                       "not a measurement.")),

    f(id       = "frontier-coefficients-focused",
      paperId  = NA_character_,
      title    = "What each frontier term contributes, on a common footing",
      builder  = "figFrontierCoefficientsFocused",
      sources  = "frontier.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Contribution of each frontier term to the linear predictor,",
                       "beta x SD of the term, in logits, with 95% intervals. Drivers",
                       "and interaction factors are standardized to unit SD so their",
                       "contribution equals their coefficient; the logistic time trend",
                       "is a raw logistic in [0,1] over 2001-2022 and is scaled by its",
                       "own standard deviation. Triangles are interactions."),
      shows    = paste("The relative magnitude of every term on a footing where the",
                       "comparison is meaningful - which the raw coefficient table does",
                       "NOT provide."),
      reads    = paste("The time trend is the largest single term in both sectors, but",
                       "by ~3x Government Effectiveness in Bulk and ~1x in Diffuse - not",
                       "the ~39x its raw coefficient of 10.3 against 0.26 suggests. That",
                       "gap between the two readings is the reason this figure exists."),
      rails    = paste("REVISED 2026-08-18. The previous version plotted raw",
                       "coefficients on an axis labelled 'per SD' with the trend beyond",
                       "a break - which invited exactly the wrong comparison, because",
                       "the trend is not a per-SD quantity. Do NOT revert to that.",
                       "The trend is scaled, never dropped: it carries 0.658 of the Bulk",
                       "linear-predictor variance and 0.405 of Diffuse. Those numbers are",
                       "deliberately NOT drawn on the plot - the figure carries positions,",
                       "the documents carry values (MODEL.md 8.5, claims C25). Quote them",
                       "in the caption or the SI, never omit them.",
                       "For the complete term list including fixed effects use",
                       "fig-frontier-coefficients, which uses the same scaling.")),

    f(id       = "gap-relative-vs-absolute",
      paperId  = NA_character_,
      title    = "The gap has to be relative, not absolute",
      builder  = "figGapRelativeVsAbsolute",
      sources  = "frontier.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Country ranking under the absolute gap S* - S against the",
                       "relative gap 1 - S/S*, connected per country. The two",
                       "measures correlate at Spearman 0.94 at this resolution;",
                       "highlighted countries are the minority that move materially."),
      shows    = paste("Which countries the choice of gap measure actually moves - and",
                       "that at country level most of them do not."),
      reads    = paste("At COUNTRY level the two measures largely agree (Spearman",
                       "0.94), and this figure must not be used to claim otherwise.",
                       "What it shows is the handful that move several places (FRA,",
                       "DEU, GRC, ISL, BGR on Bulk). The decisive divergence is at",
                       "REGION level, where MODEL.md 5.2 makes the case: absolute gaps",
                       "span only a factor ~1.4 across regions so the ranking is",
                       "dominated by ceiling size. That region-level comparison is not",
                       "stored in any artifact and would need",
                       "aggregateFeasibilityToRegions() re-run to plot."),
      rails    = paste("Never mix the two measures in one sentence, table or figure.",
                       "Bind mode 3 uses a THIRD definition, (S*-S)/S, unbounded as S",
                       "approaches 0.")),

    f(id       = "coverage-three-ways",
      paperId  = NA_character_,
      title    = "Most of the world has never been measured",
      builder  = "figCoverageThreeWays",
      sources  = "frontier.rds,donor-assignment-band-<sector>.rds,madrat calcGDPPast",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Provenance of every projected country's feasibility value, by",
                       "country count and by share of world GDP. Three groups: observed,",
                       "donor-matched, rule-placed. The GDP bar is subdivided by",
                       "contributors above 2% of world output, because what remains",
                       "uncovered is a small number of very large economies rather than a",
                       "diffuse remainder."),
      shows    = paste("That a single coverage number misleads in whichever direction it",
                       "is quoted, and where the uncovered economic weight actually sits."),
      reads    = paste("48 of 248 countries are observed - 19% by count but 65% of world",
                       "GDP, because the measured set includes China, India and most large",
                       "economies. The rule-placed group is 27% of world GDP and the United",
                       "States alone is most of it: the largest economy in the world has no",
                       "policy-stringency data at all."),
      rails    = paste("GDP here is a REPORTING weight only. The coupling weights countries",
                       "by emissions-proxy FINAL ENERGY (MODEL.md 5.4), and every",
                       "feasibility share reported in this work is energy-weighted, not",
                       "GDP-weighted - say so if a GDP figure is quoted. NOTE the GDP levels",
                       "come from the madrat cache, not a Run-Group artifact: the panel's",
                       "GDP column is transformed and its shares are meaningless, so this",
                       "figure is the one deliberate exception to artifacts-only.")),

    f(id       = "influence-loro",
      paperId  = NA_character_,
      title    = "What survives dropping any single country",
      builder  = "figInfluenceLoro",
      sources  = "influence.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Full-sample cluster-robust p-value per term with the range across",
                       "all 48 leave-one-country-out refits, log scale. Countries marked",
                       "with a minus destroy a finding when removed; countries marked with",
                       "a plus would create significance if removed. Only the first is a",
                       "fragility."),
      shows    = paste("Which coefficient claims are robust to the removal of any one",
                       "country, in which direction, and exactly which countries are",
                       "responsible."),
      reads    = paste("State capability in both sectors, fossil incumbency on the demand",
                       "side, and the bulk-side innovator-capability substitution carry no",
                       "pivotal country. Bulk Horizontal Accountability is destroyed by ISL,",
                       "PER or ZAF - but through SE inflation of 9-37%, not coefficient",
                       "movement, so it is a precision failure rather than a leverage one.",
                       "Saudi Arabia only ever suppresses: all three of its crossings are",
                       "gains, and only two survive the wild-cluster bootstrap."),
      rails    = paste("LOSS and GAIN are opposite findings and must never be reported as",
                       "one count. A term that was never significant trivially has a",
                       "worst-case p above alpha and is NOT a fragile finding. Crossings are",
                       "screened on the ASYMPTOTIC p; the wild-cluster bootstrap is the",
                       "quotable inference here and it does not confirm every crossing -",
                       "Innovator Power drop-SAU is p_wild 0.083, not significant. A term",
                       "with a loss-pivotal country may not be claimed at all; report the",
                       "coefficient with its leave-one-out range, never a point p.")),

    f(id       = "scenario-fanout",
      paperId  = NA_character_,
      title    = "The projected ceiling responds to the pathway",
      builder  = "figScenarioFanout",
      sources  = "projections/<scenario>.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Median projected stringency across in-coverage countries by",
                       "scenario and sector, interquartile ribbon. Separation between",
                       "the scenarios is the feedback channel operating; the late",
                       "horizon is greyed because scenario differences past roughly",
                       "2060 are not interpretable."),
      shows    = paste("That the feedback channel is alive - the reason the split",
                       "actor-power form is load-bearing and the composite was",
                       "rejected."),
      reads    = paste("Read the separation, not the levels. Under the composite",
                       "actor-power form both pathways winsorized to the same boundary",
                       "and this fan-out collapsed to one line."),
      rails    = paste("Do not read past ~2060: the guard-winsorized driver share",
                       "grows large late-century. The divergence is conditional",
                       "scenario accounting, not an identified causal effect.")),

    f(id       = "temporal-validation",
      paperId  = NA_character_,
      title    = "The level forecast loses to persistence",
      builder  = "figTemporalValidation",
      sources  = "temporal-validation.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Pseudo-out-of-sample validation: fit on 2001-2015, recursively",
                       "forecast 2016-2022, one point per country-year against the",
                       "45-degree line. Skill against a persistence benchmark is",
                       "negative in both sectors."),
      shows    = paste("The negative result that shapes the entire design - why the",
                       "model delivers ceilings and speeds and never projected level",
                       "paths."),
      reads    = paste("Points scatter widely around the diagonal and the model is",
                       "beaten by assuming no change. This is reported deliberately,",
                       "not buried."),
      rails    = paste("This is a headline honesty exhibit. Do not replace it with the",
                       "four-sector speed figure, which shows electricity in a better",
                       "light - they answer different questions.")),

    f(id       = "chain-schematic",
      paperId  = "Fig 1a",
      title    = "From institutions to a bounded carbon price",
      builder  = "figChainSchematic",
      sources  = "conceptual",
      consumers= "paper,slides,poster",
      status   = "built",
      caption  = paste("Schematic of the mechanism: institutions and actor coalitions set a",
                       "ceiling on policy stringency; a polity's distance below its own",
                       "ceiling becomes a feasibility share applied to the incremental",
                       "mitigation effort an ambitious pathway demands. The dashed return",
                       "arrow is the feedback: deployment shifts actor power, which shifts",
                       "the ceiling."),
      shows    = paste("The whole argument in one picture, including where the loop closes",
                       "- the part most often lost when the model is explained verbally."),
      reads    = "Nothing. It carries no data and must not be read as if it does.",
      rails    = paste("Conceptual. No axes, no scale, no numbers, and no Run-Group stamp.",
                       "The feedback arrow is labelled as conditional scenario accounting",
                       "because the IV identifies no significant causal effect (MODEL.md",
                       "8.1) - do not relabel it as causal.")),

    f(id       = "anchor-bound-gap",
      paperId  = "Fig 3a",
      title    = "Anchor, feasible bound, and the gap between them",
      builder  = "figAnchorBoundGap",
      sources  = "coupling/coupling-summary.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Cost-optimal carbon-price anchor (dashed), the politically feasible",
                       "bound (solid) and the gap between them (shaded), 2025-2100, for four",
                       "REMIND regions spanning the feasibility distribution. Regions are",
                       "selected at evenly spaced positions in the phi ordering, so the panel",
                       "always includes the most and least constrained region and is not",
                       "hand-picked."),
      shows    = paste("Where the shortfall summarised in Figs 3b and 3c comes from, in price",
                       "space and over time."),
      reads    = paste("The gap widens as the anchor rises: the constraint bites hardest",
                       "exactly when ambition is highest. Compare panels left to right to see",
                       "how much of that is the feasibility share rather than the price path."),
      rails    = paste("This is the PFM-side BOUND, not a coupled REMIND result - it is what",
                       "the ceiling says before the model re-optimises, and it must never be",
                       "presented as what REMIND does when it feels the ceiling (that is the",
                       "coupled-* figure set). Levels scale with theta; the figure prints the",
                       "value it used.")),

    f(id       = "implementability-ranked",
      paperId  = "Fig 4b",
      title    = "How robust the region ordering is, as rank intervals",
      builder  = "figImplementabilityRanked",
      sources  = "frontier-rung-phi.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Rank of each EU21 region's delivered feasibility share across the four",
                       "fitted frontier variants (headline half-normal, truncated-normal, panel,",
                       "time-decay), as the range of ranks with the median marked. Rank 1 is the",
                       "least constrained region."),
      shows    = paste("How much of the region ordering survives the frontier's error structure:",
                       "the widest interval spans 13 ranks of 20 and only 40% of regions sit clear",
                       "of the middle of the field."),
      reads    = paste("Read a WIDE bar as 'this region's position is a modelling choice' and a",
                       "narrow one as 'the rungs agree'. The dashed line is the middle of the",
                       "field; a region whose whole interval sits on one side of it is marked as",
                       "separable."),
      rails    = paste("🔴 THE INTERVAL IS NOT A CONFIDENCE INTERVAL - it is the range over four",
                       "fitted models, and calling it 95% would invent a sampling statement.",
                       "Re-pointed here 2026-09-18 (TODO item 37) because claim C11 forbids naming",
                       "a country from a point ranking on `v5`; the country point version is",
                       "`implementability-ranked-countries`, report and slides only. Delivered phi",
                       "is the min() of the two sectors - the quantity the coupling consumes - so",
                       "this panel answers a different question from Fig 1c.")),

    f(id       = "implementability-ranked-countries",
      paperId  = NA_character_,
      title    = "Every in-coverage country, ranked, both sectors on one scale",
      builder  = "figImplementabilityRankedCountries",
      sources  = "frontier.rds",
      consumers= "slides,report",
      status   = "built",
      caption  = paste("Efficiency ratio E = S/S* at 2022 for the 48 in-coverage countries,",
                       "both sectors on one axis, with the conditional slack band and sector",
                       "medians. Rows are ordered by the Diffuse value."),
      shows    = paste("How far each country sits below its OWN ceiling, and that the two",
                       "sectors disagree within a country - the split the coupling turns on."),
      reads    = paste("Read the horizontal distance between a country's two points, not its",
                       "absolute position. Diffuse sits lower than Bulk for most countries,",
                       "which is why the min() sector rule usually resolves to Diffuse."),
      rails    = paste("NOT A PAPER FIGURE (moved out of Fig 4b on 2026-09-18): claim C11 forbids",
                       "naming a country from a point ranking on `v5`. ORDERED BY DIFFUSE ON",
                       "PURPOSE - Bulk slack ranks do not survive the robustness battery (rank",
                       "correlation 0.154 on the panel rung against 0.854 / 0.579 for Diffuse,",
                       "MODEL.md 3.4). Bulk points are shown for within-country comparison and",
                       "must NEVER be read as a Bulk country ranking. The `region` column holds",
                       "ISO3 COUNTRY codes; this is 48 countries, not 21 REMIND regions.")),

    f(id       = "coverage-by-region",
      paperId  = "Fig 4c",
      title    = "How much of each REMIND region was ever measured",
      builder  = "figCoverageByRegion",
      sources  = "coupling/coupling-summary.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Share of each REMIND region's weight that falls inside the",
                       "48-country estimation sample. The remainder inherits a transferred",
                       "relative gap through the donor and band rules, never a measured",
                       "ceiling. China and the United States are annotated."),
      shows    = paste("That coverage is far better by energy than by country count - 11 of",
                       "21 regions are fully covered and only two sit below 20% - so the",
                       "limitation is about the SAMPLE, not about the share of the world the",
                       "frontier can speak to. It concentrates on one region: the USA."),
      reads    = paste("Read which regions are short. Only USA (0%) and SSA (14%) are below",
                       "20%; then MEA 23%, OAS 40%, LAM 41%. China is 96% covered. The United",
                       "States at 0% is the acute case - its feasibility share is pinned by a",
                       "basis override and must be reported as a RANGE, not a point."),
      rails    = paste("DO NOT quote a CHA figure from any artifact written before",
                       "2026-08-18: the 31.8% that appeared here, and the reading \"China is",
                       "two-thirds unobserved\", were artefacts of a broken aggregation weight",
                       "(PITFALLS.md 20) and are DEAD. The figure stamps NOT QUOTABLE when the",
                       "artifact's weight fails the size check. Coverage is a property of the",
                       "data, not a result - do not present it",
                       "as a finding about those regions. The USA at 0% compounds with two",
                       "other fragilities on the same region: the basis-rule sensitivity that",
                       "moves it across the entire scale (TODO item 6, claims C18) and its",
                       "position on the theta floor in every coupled run (claims C21). Any US",
                       "claim must carry all three. Distinct from `coverage-three-ways`, which",
                       "cuts the same limitation by country count and world GDP rather than",
                       "by REMIND region - they are not substitutes.")),

    f(id       = "marginal-effect-incumbency",
      paperId  = "Fig 2b",
      title    = "Does incumbency act through institutions?",
      builder  = "figMarginalEffectIncumbency",
      sources  = "frontier.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Marginal effect of incumbent power on the estimated ceiling as",
                       "government effectiveness varies, both sectors, with 95% intervals",
                       "computed from the full coefficient covariance matrix. The horizontal",
                       "axis spans the OBSERVED range of the moderator and stops there; the",
                       "shaded band is its interquartile range. The second actor-power",
                       "interaction is held at its sample mean."),
      shows    = paste("Whether actor power acts THROUGH institutions rather than around",
                       "them - the claim in C9, which is about a marginal effect and cannot",
                       "be read off a coefficient table."),
      reads    = paste("Read where the interval excludes zero, not the slope alone. A curve",
                       "that crosses zero inside the observed range means incumbency helps in",
                       "some institutional settings and hinders in others, which is the",
                       "conditionality the paper claims."),
      rails    = paste("The interval REQUIRES Cov(beta_focal, beta_interaction) - at v1 that",
                       "covariance is -0.00119 in Bulk, so an interval built from the two",
                       "standard errors alone is wrong, not merely approximate. This figure",
                       "was impossible until runPFMFrontier() began persisting $vcov and",
                       "$support (2026-08-18); do not reintroduce a version that assumes a",
                       "+/-3 SD window or drops the covariance. Never extend the axis beyond",
                       "the observed support - MODEL.md 2.7. And note this is one conditional",
                       "slice: the Incumbent x Horizontal Accountability term is held at its",
                       "mean, so the curve is not a total derivative.")),

    f(id       = "driver-correlations",
      paperId  = NA_character_,
      title    = "Correlation among the model terms",
      builder  = "figDriverCorrelations",
      sources  = "frontier.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("Pearson correlation among model terms on the estimation rows, fixed",
                       "effects excluded. Bulk below the diagonal, Diffuse above it; the two",
                       "sectors are fitted on different rows so the halves are not symmetric.",
                       "The diagonal carries the term names."),
      shows    = paste("Why the selection bootstrap cannot separate the institutional",
                       "channels - the direct evidence behind C17's 29.4% channel-set",
                       "frequency and its 0.5-point lead over the runner-up."),
      reads    = paste("Look for strong off-diagonal blocks among the institutional terms.",
                       "Where two channels correlate strongly, a resample can swap one for",
                       "the other at almost no cost in fit, which is exactly what the",
                       "bootstrap reports."),
      rails    = paste("This is the figure form of the correlation tables the old reports",
                       "carried. It documents a LIMITATION, not a result - do not present a strong correlation as a",
                       "finding about politics. Correlation is polarity data, so the scale is",
                       "diverging with a neutral midpoint at zero; do not swap it for a",
                       "sequential ramp. Values are printed in every cell so the encoding is",
                       "never colour-alone.")),

    f(id       = "estimator-agreement",
      paperId  = NA_character_,
      title    = "Do the coefficient signs survive a change of estimator?",
      builder  = "figEstimatorAgreement",
      sources  = "estimator-agreement.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("Number of estimators returning a positive or negative coefficient for",
                       "each model term, out of up to seven (satP, fractional, beta, levels,",
                       "satP-re, satP-yearFE, levels-twfe), both sectors. A bar lying entirely",
                       "on one side means the sign is stable across estimator choice. The",
                       "count beside each bar is how many estimators find the term",
                       "significant at 5%."),
      shows    = paste("A harsher robustness test than a p-value: a p-value is computed WITHIN",
                       "one estimator, this asks whether the direction survives changing it."),
      reads    = paste("Only three of thirteen terms hold their sign across every estimator",
                       "that fits them. Sign stability and significance are independent -",
                       "Government Effectiveness is significant in 7 of 7 and still flips once."),
      rails    = paste("Do not read the bar positions as identifying WHICH estimator gave",
                       "which sign - the artifact records the sign string but not the mapping",
                       "from position to estimator, and terms fitted by fewer estimators give",
                       "shorter strings. Counting is all the data supports. Any directional",
                       "claim about a term whose bar spans both sides is not robust to",
                       "estimator choice and must be worded accordingly.")),

    f(id       = "historical-replay",
      paperId  = NA_character_,
      title    = "The replay gate, and what it does not prove",
      builder  = "figHistoricalReplay",
      sources  = "historical-replay.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("Root-mean-square error against observed policy stringency when the",
                       "coupled system is replayed over history from a 2000 seed, against an",
                       "uncoupled error-correction model and a no-change baseline, both",
                       "sectors, 1056 country-years. The share of rows in which the ceiling",
                       "actually binds is printed on each panel."),
      shows    = paste("That the coupled system is not WORSE than the uncoupled model",
                       "in-sample - and that the margin is tiny because the constraint is",
                       "almost never active over the historical window."),
      reads    = paste("Compare the coupled bar with the ECM bar, not with persistence. The",
                       "gain over the ECM is +0.003 in Bulk and +0.038 in Diffuse, and the",
                       "ceiling binds in only 1.6% and 4.0% of rows."),
      rails    = paste("This gate RULES OUT A BROKEN COUPLING; it does not validate the",
                       "ceiling. Out of sample the binding share is an order of magnitude",
                       "larger (84.5% of region-years), and nothing here speaks to that",
                       "regime. Do not present the persistence comparison as the headline -",
                       "persistence is a very weak baseline over 22 years and beating it is",
                       "not evidence for the mechanism. MODEL.md 8.4.")),

    f(id       = "sharing-cost",
      paperId  = NA_character_,
      title    = "What one shared specification costs each sector",
      builder  = "figSharingCost",
      sources  = "selection-variants.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("Theory content (ΔR²) of the deployed shared specification against the",
                       "best specification each sector could have chosen on its own. The gap",
                       "is the price of requiring one functional form across both sectors."),
      shows    = paste("That the shared-specification design choice is not free, and that its",
                       "cost falls very unevenly between the two sectors."),
      reads    = paste("Bulk gives up 4.9% of achievable theory content, Diffuse 24.9%. The",
                       "deployed form sits close to Bulk's own optimum and far from Diffuse's",
                       "- so it is in effect a Bulk specification that Diffuse is made to",
                       "wear."),
      rails    = paste("This is a DESIGN CHOICE with a measurable price, not a defect: a",
                       "shared form is what makes the two sectors comparable and the maximin",
                       "rule meaningful. But the asymmetry matters, because Diffuse is the",
                       "sector that usually binds in the coupling and therefore carries the",
                       "headline result. Third leg of the selection-honesty set with",
                       "selection-stability (resampling) and selection-landscape (this",
                       "sample).")),

    f(id       = "selection-landscape",
      paperId  = NA_character_,
      title    = "Where the deployed specification sits among its alternatives",
      builder  = "figSelectionLandscape",
      sources  = "sweep.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Every candidate Policy Stringency specification in the sweep, plotted",
                       "by theory content (minimum ΔR² across sectors) against fit (sum BIC",
                       "across sectors, lower is better). Grey points fail the admissibility",
                       "gate; blue points pass it; the deployed specification is circled. The",
                       "shaded band is a +/-0.002 tie interval on the theory criterion."),
      shows    = paste("How much better than its alternatives the deployed specification",
                       "actually was on THIS sample - the question Fig 2c's resampling result",
                       "presupposes but does not answer."),
      reads    = paste("Read the TRADE-OFF, not the position. Theory content and fit pull",
                       "against each other: the best-fitting admissible specs cluster near",
                       "BIC 4750-4850 with only 0.03-0.07 theory content, while everything at",
                       "high theory content sits at BIC 4950-5250. The deployed spec is at",
                       "the right-hand edge on theory and mid-field on fit - of 242 admissible",
                       "specs, 159 fit better, 43 have higher mean theory content, and 8 more",
                       "are inside the tie band. It is selected by a rule, not by dominating."),
      rails    = paste("Do NOT read the rule as 'maximise minimum deltaR2' - four admissible",
                       "specs lie to the RIGHT of the deployed one and would look like an",
                       "error under that reading. They rank 10, 26, 39 and 44 because the",
                       "maximin rule is multi-criteria: worse-sector tier first, then theory",
                       "content, then parsimony and fragility tie-breaks. State the rule when",
                       "showing this. Pair it with selection-stability (Fig 2c): this figure",
                       "is about THIS sample, that one about resamples, and the honest claim",
                       "needs both.")),

    f(id       = "iv-null",
      paperId  = NA_character_,
      title    = "Endogeneity confirmed, causal effect not identified",
      builder  = "figIVNull",
      sources  = "iv.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Two-stage least-squares estimates of the incumbent-power effect on",
                       "policy stringency with 95% confidence intervals, using a shift-share",
                       "instrument (base-year incumbency interacted with leave-one-out global",
                       "VRE diffusion), for both sectors with and without the time trend.",
                       "First-stage F statistics are printed beside each estimate."),
      shows    = paste("That the endogeneity the model is accused of is REAL and confirmed,",
                       "and that the instrument establishing it cannot identify a causal",
                       "effect - the honesty claim the whole feedback story rests on."),
      reads    = paste("Every interval crosses zero while Wu-Hausman rejects exogeneity at",
                       "p about 1e-53. Read the two together: OLS cannot be given a causal",
                       "reading, and 2SLS cannot replace it."),
      rails    = paste("This is a NULL, and it must be presented as one - it is the reason",
                       "every mention of the feedback loop says 'conditional scenario",
                       "accounting' and never 'causes' (MODEL.md 8.1). The no-trend rungs are",
                       "WEAKLY INSTRUMENTED (first-stage F 4.6 and 4.9); their wider",
                       "intervals are weak instrumentation, not evidence of a larger effect,",
                       "and they are faded on the figure for that reason. Do not quote them",
                       "as a sensitivity that 'nearly' reaches significance.")),

    f(id       = "coupled-convergence",
      paperId  = NA_character_,
      title    = "Did the feasibility share converge?",
      builder  = "figCoupledConvergence",
      sources  = "coupling/coupled-runs.rds",
      consumers= "report,slides",
      status   = "built",
      caption  = paste("Maximum change in the regional feasibility share between successive",
                       "PFM coupling calls, log scale, one line per coupled run, both",
                       "resolutions. The dashed line is the convergence tolerance, cm_pfmConvTol = 0.002.",
                       "Consecutive duplicate values are collapsed, so each point is one",
                       "coupling call rather than one Nash iteration."),
      shows    = paste("The difference between a run that DEMONSTRATES convergence with a",
                       "contracting sequence and one that merely crosses the tolerance on its",
                       "first comparison."),
      reads    = paste("On Run-Group v5 the PFM is called 3-8 times per run: 30 of 36 sequences",
                       "contract strictly, and the six rule-C runs oscillate before settling.",
                       "Every run ends below 0.002 (SCENARIOS.md 3.2)."),
      rails    = paste("A single point below the tolerance is CONSISTENT with convergence,",
                       "not evidence of it - report the sequence. Convergence of the PFM loop",
                       "says nothing about REMIND's budget loop (SCENARIOS.md 4.3).")),

    # ---- the coupled results (Run-Group v5 batch) ---------------------------
    # PURE CONSUMERS of coupling/coupled-runs.rds, which analysis/coupled/extractCoupledResults.R
    # writes from output/remind-runs/. If that artifact is missing, run the extractor - do not read the
    # gdx from a builder.

    f(id       = "coupled-sector-split",
      paperId  = "Fig 5a",
      title    = "Where the political constraint lands",
      builder  = "figCoupledSectorSplit",
      sources  = "coupling/coupled-runs.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Regional carbon price in 2050 under the ratio bind mode, EU21,",
                       "theta = 0.50, ordered by feasibility share. ETS emissions",
                       "(electricity and industry) face pm_taxCO2eq plus the ETS markup;",
                       "ES emissions (buildings and transport) pay it plus their OWN markup -",
                       "since ADR 0042 made the markup symmetric, pm_taxCO2eq alone is the",
                       "price NEITHER market pays. The carbon budget is held (peak cumulative",
                       "CO2 1001.5 Gt against a 1000 Gt peak budget), so the contrast is not",
                       "confounded by a different mitigation level."),
      shows    = paste("That politics separates the two sectors' prices WITHIN a region by up",
                       "to 1.5x, and that the direction is region-specific rather than",
                       "uniformly anti-household. This is the contrast a one-price coupling",
                       "could not represent at all."),
      reads    = paste("Read the split WITHIN each row, never off the two columns' min and",
                       "max. At EU21 2050 (Run-Group v5), 15 of 21 regions price households",
                       "BELOW industry and 6 above; Central Europe pays 0.66x on ES against",
                       "ETS and Russia 1.37x. H12 runs 0.70-1.31, 9 of 12 below. The ordering",
                       "is by phi, so the constraint biting is the trend down the panel."),
      rails    = paste("NEVER add the two prices - each is a floor plus that market's own",
                       "increment, so their sum is meaningless (COUPLING.md 11.6).",
                       "DO NOT say the constraint lands on households: it does so in most",
                       "regions and not in six, including Russia; median ES/ETS 0.965.",
                       "The finding is the WIDTH and the region-specificity, not a direction.",
                       "NO region is pinned at a legislated price floor:",
                       "cm_taxCO2_lowerBound_path_gdx_ref is 0 on all 48 runs (SCENARIOS.md 6.3).",
                       "THE MAGNITUDE IS CONDITIONAL ON LAMBDA: at the deployed lambda = 0 the",
                       "regional spread is 1.88x and ES/ETS runs 0.66-1.37; at the frontier's",
                       "estimated rate it is 1.10x and 0.92-1.03 (SCENARIOS.md 1.2). It is ALSO",
                       "conditional on cm_pfmSectorMarkup = 1, and the anchor rises 1.33x to pay",
                       "for it (SCENARIOS.md 4.1).")),

    f(id       = "frontier-vs-observed",
      paperId  = "SI-10",
      title    = "The fitted ceiling against observed policy, by country",
      builder  = "figFrontierVsObserved",
      sources  = "frontier.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("Policy stringency index 2001-2022 for the 48 in-coverage countries,",
                       "demand-side sector. Dashed: the ceiling fitted by the stochastic",
                       "frontier. Solid: the observed index. Shaded: the unused space, which",
                       "is the model's slack term. Panels are ordered by mean use of the",
                       "ceiling, most first; the y-scale is fixed because the index is a",
                       "common 0-10 scale and the level is the point."),
      shows    = paste("The frontier itself, one country at a time. Every aggregate in the",
                       "paper is a summary of this panel - the efficiency ratio is the ratio",
                       "of the two lines, the slack is the gap, and phi is a min-max",
                       "normalisation of that gap across regions."),
      reads    = paste("Find a country, then read the GAP rather than either line. A wide gap",
                       "is unused political space, not a prediction that the country will",
                       "close it. The ordering is the finding: the top panels sit near their",
                       "own ceiling while the bottom ones leave most of it unused."),
      rails    = paste("Observed EXCEEDS the fitted ceiling in a few country-years, and those",
                       "points are drawn rather than clipped - a stochastic frontier has a",
                       "two-sided noise term, so points above the frontier are expected and",
                       "their frequency is diagnostic. Do NOT describe the ceiling as a",
                       "maximum. This is the FITTED ceiling; the coupling consumes the",
                       "PROJECTED one, which is a different object - see `frontier-projected`",
                       "and note the seam between them.")),

    f(id       = "frontier-projected",
      paperId  = "SI-11",
      title    = "The ceiling fitted, then projected under two scenarios",
      builder  = "figFrontierProjected",
      sources  = "frontier.rds, projections/SSP2-PkBudg1000-PFMref.rds, projections/SSP2-NPi2025-PFMbase.rds",
      consumers= "paper,report",
      status   = "built",
      caption  = paste("The same 48 countries and the same index as SI-10, carried forward.",
                       "Grey solid: observed to 2022. Grey dashed: the fitted ceiling.",
                       "Coloured: the ceiling projected to 2100 under the ambitious and the",
                       "current-policies pathway, with the projection interval shaded. The",
                       "two halves are deliberately not joined."),
      shows    = paste("What the coupling actually consumes. phi is computed from the",
                       "PROJECTED ceiling at the seed year, not from the fitted one, so this",
                       "is the object that reaches REMIND. It also shows the scenario",
                       "dependence behind claim C5: the ceiling is a function of scenario",
                       "drivers, so ambition moves the ceiling it runs into."),
      reads    = paste("Read the two coloured lines against each other within a panel, not",
                       "across panels. The fan between them is the scenario effect and it is",
                       "small relative to the between-country spread."),
      rails    = paste("🔴 THE SEAM IS REAL. Across 2022/2025 the ceiling steps DOWN in all 48",
                       "in-coverage countries - but that comparison was WRONG and has been",
                       "retracted. frontierIndex is the SFA frontier (a CEILING) and index is",
                       "projected policy stringency (a LEVEL); the apparent step was the",
                       "model's slack term. Against the right counterpart the projection is",
                       "continuous: 2025 index vs 2022 observed is +0.95 index points. The",
                       "figure now plots the LEVEL as one series and the ceiling separately",
                       "(PITFALLS.md 21, TODO item 10).",
                       "NEVER join the dashed ceiling to the solid level - they are different",
                       "quantities. The level itself IS continuous and is drawn as one series.",
                       "Out-of-coverage countries are",
                       "EXCLUDED: they carry a transferred relative gap, not a measured",
                       "ceiling, and plotting them beside observed data would imply evidence",
                       "that does not exist.")),

    f(id       = "frontier-by-region",
      paperId  = "SI-12",
      title    = "The ceiling summarised over REMIND regions",
      builder  = "figFrontierByRegion",
      sources  = "regional-frontier.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Final-energy-weighted mean of the country ceilings over the 21 REMIND",
                       "regions, demand-side sector: observed and fitted to 2022, then",
                       "projected to 2100 under both scenarios. The percentage beside each",
                       "region is the share of its final energy that has a measured ceiling."),
      shows    = paste("The same object as SI-10/SI-11 at the resolution phi is ASSIGNED on,",
                       "rather than the resolution the frontier is FITTED on. It also makes",
                       "the coverage limitation structural rather than a footnote: the United",
                       "States panel is empty because no US country-year is in the estimation",
                       "sample at all."),
      reads    = paste("Read the percentage first, then the lines. A region at 41% is a claim",
                       "about two-fifths of its energy. Sixteen of twenty regions are at or",
                       "above 73%; LAM (41%), OAS (40%), MEA (23%) and SSA (14%) are thin and",
                       "their lines should not be quoted without that number beside them."),
      rails    = paste("🔴 NOT a rescaled view of SI-10/SI-11 and not a substitute for them.",
                       "Two reasons: u is min-max normalised over whatever units are in frame,",
                       "so aggregating CHANGES THE OBJECT - the same effect that moves the",
                       "anchor from 0.744 over 48 countries to 0.396 over 21 regions",
                       "(PITFALLS.md 15); and the frontier is non-linear, so a weighted mean",
                       "of ceilings is not the ceiling of the mean. NO REGIONAL FRONTIER WAS",
                       "EVER FITTED - every line is a summary of country ceilings and must be",
                       "described as one. Out-of-coverage countries are excluded, so the lines",
                       "describe the covered share only. The 2022/2025 seam of SI-11 is present",
                       "here too (TODO item 10).")),

    f(id       = "markup-counterfactual",
      paperId  = "Fig 5d",
      title    = "The markup-off twin: what the second instrument does",
      builder  = "figMarkupCounterfactual",
      sources  = "coupling/coupled-runs.rds",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Regional carbon price in 2050, EU21, theta = 0.50, budget held,",
                       "ordered by feasibility share. Two exact twins differing in one",
                       "switch: cm_pfmSectorMarkup = 1 (left) and 0 (right). With the markup",
                       "off REMIND receives only min(phi_Bulk, phi_Diffuse) and prices a",
                       "single number, so the dumbbell collapses to one dot per region."),
      shows    = paste("Two things at once. That the sector split is the frontier's",
                       "Bulk/Diffuse structure delivered through the markup rather than an",
                       "artefact of REMIND having two markets - remove the channel and the",
                       "distinction is DISCARDED, not corrected. And that with one instrument",
                       "the constraint stops binding: the median region returns to the",
                       "cost-optimal anchor and the maximum overshoots it by 1.41x."),
      reads    = paste("Read row by row, left to right. The left panel fans out; the right",
                       "collapses onto the dashed anchor line and past it. Median ES moves",
                       "$199 -> $251 at EU21 against a $253 anchor (H12: $174 -> $266 against",
                       "$247). That is claim C20's self-defeating behaviour, isolated."),
      rails    = paste("This is an ATTRIBUTION figure, not a scenario comparison - the",
                       "markup-off run is a counterfactual and is not a policy the paper",
                       "proposes. Do not present the right panel as a result in its own",
                       "right. The builder ASSERTS cm_pfmSectorMarkup is 1 and 0 in the two",
                       "runs and errors otherwise, because a mislabelled twin would draw a",
                       "convincing wrong picture. Claims C32, and C20's confirmation.")),

    f(id       = "coupled-relocation",
      paperId  = "Fig 5d",
      title    = "Where the abatement goes",
      builder  = "figCoupledRelocation",
      sources  = "coupling/coupled-costs.json",
      consumers= "paper,slides,report",
      status   = "built",
      caption  = paste("Change in cumulative CO2eq 2020-2100 by region against each run's",
                       "matched theta = 0 null, for the budget-held run (-PFMratio) and the",
                       "capped run on the pinned price path (-PFMlevelBfix), both resolutions,",
                       "theta = 0.50. Regions are ordered by their feasibility share."),
      shows    = paste("That a held budget RELOCATES abatement rather than reducing it (net a few",
                       "Gt against 72-81 Gt moved), and that when the price path is held instead",
                       "the extra emissions concentrate in the most constrained regions (C36, C37)."),
      reads    = paste("Read the bars against the ordering: they lengthen towards the top, where",
                       "phi is lowest. That shape IS the reported rank correlation. Read the two",
                       "colours as two closures of one question, not as two scenarios."),
      rails    = paste("EMISSIONS ONLY. The GDP and consumption effects are deliberately not",
                       "drawn: REMIND carries no climate damages, so a run that abates less always",
                       "looks richer, and a GDP bar beside an emissions bar invites exactly that",
                       "misreading (C37). The relocation exists BECAUSE the political gap persists",
                       "- with gap closure it falls to 6-7 Gt (C36). CHA emitting less under the",
                       "cap is a general-equilibrium response, not a political one.")),

    f(id       = "coupled-budget-cost",
      paperId  = "Fig 5b",
      title    = "What political feasibility costs the carbon budget",
      builder  = "figCoupledBudgetCost",
      sources  = "coupling/coupled-runs.rds",
      consumers= "paper,slides,poster,report",
      status   = "built",
      caption  = paste("Cumulative CO2 emissions 2020-2100 under the level cap (-PFMlevelBfix)",
                       "against its matched theta = 0 null (-PFMgateBfix), at both region",
                       "resolutions. Both read the anchor that -PFMgate converged to and switch",
                       "budget forcing off, so the null MEETS the 1000 Gt budget and the gap is",
                       "the extra CO2 the political ceiling adds to that pathway."),
      shows    = "The quantity headline: what political feasibility adds to the 1000 Gt pathway at theta = 0.50 (claim C35).",
      reads    = paste("The two resolutions are independent aggregations - read their agreement",
                       "as agreement in size, not a replication. Quote it with the declared theta",
                       "range and the gap-closure arm (SCENARIOS.md 4.2a)."),
      rails    = paste("Both runs are cm_iterative_target_adj = 0, the family in which the",
                       "EU legislated-price floor is NOT applied (PITFALLS.md 17). The",
                       "comparison is valid but its price LEVELS are not comparable with the",
                       "ratio runs in Fig 5a. Quote it with the theta range, never alone. The",
                       "unforced-anchor pair (-PFMlevelB / -PFMgateB) is the SI sensitivity:",
                       "pass run/null to draw it, and label it as such (claim C19).")),

    f(id       = "coupled-npi-twins",
      paperId  = "Fig 5c",
      title    = "The mechanism is not an artefact of high ambition",
      builder  = "figCoupledNpiTwins",
      sources  = "coupling/coupled-runs.rds",
      consumers= "paper,slides,report",
      # figCoupledNpiTwins() refuses to build when any twin is missing: every bar is a
      # difference, so an absent run renders as an absent bar rather than an error. On
      # 2026-09-13 that drew an empty panel under a headline asserting six bars. The runs
      # landed 2026-09-14 (SCENARIOS.md 4.7); keep the guard.
      status   = "built",
      caption  = paste("Change in cumulative CO2 to 2100 for each bind mode on the",
                       "current-policies pathway, measured against the theta = 0 null",
                       "(-NPi2025-PFMgate), at both resolutions. The red bar is the effect of",
                       "switching cm_taxCO2_regiDiff from 6 to 11 with no political",
                       "constraint at all - the confound incurred by measuring against the",
                       "uncoupled baseline instead."),
      shows    = paste("That all three mechanisms push the same way on a non-ambitious",
                       "pathway, and that the choice of control decides the SIGN of the",
                       "result."),
      reads    = paste("Blue bars are the effect of politics and are all positive. The red",
                       "bar is six to seven times the R and L bars and negative, so using the",
                       "uncoupled baseline as the null would report politics as REDUCING",
                       "emissions. The L twin (+131 / +158 Gt) lands within 2-6% of headline B."),
      rails    = paste("Nothing in the NPi family may be quoted against the uncoupled",
                       "SSP2[-EU21]-NPi2025 (claims C22). The mode M bar is much larger than",
                       "modes R and L and must not be read as corroborating them - modes L",
                       "and M do not agree (claims C19c)."))
  )

  if (!is.null(consumers)) {
    keep <- vapply(reg$consumers, function(c)
      any(strsplit(c, ",", fixed = TRUE)[[1]] %in% consumers), logical(1))
    reg <- reg[keep, , drop = FALSE]
  }
  if (!is.null(status)) reg <- reg[reg$status %in% status, , drop = FALSE]
  rownames(reg) <- NULL
  reg
}

#' One registry row, or stop with a useful message
figureEntry <- function(id) {
  reg <- figureRegistry()
  hit <- reg[reg$id == id, , drop = FALSE]
  if (!nrow(hit)) {
    stop("unknown figure '", id, "'. Known: ", paste(reg$id, collapse = ", "), call. = FALSE)
  }
  as.list(hit[1, ])
}
